"""Metadata and payload validation."""

import collections.abc as col
from typing import Any

import gmcodec.model as my_model

# signed i32 limits
MIN_I32 = -2147483648
MAX_I32 = 2147483647

GMSPR_VER = 800
GMBCK_VER = 710
GMBCK_IM_VER = 800


class CodecValidationError(ValueError):
    """Metadata validation error."""

    def __init__(
        self,
        field: str,
        value: Any,  # noqa: ANN401
        expected: str | None = None,
        message: str | None = None,
    ) -> None:
        """Metadata validation error.

        :param field: Invalid field name.
        :param value: Invalid field value.
        :param expected: Expected value (where applicable).
        :param message: Error message (autogenerated by default).
        """
        self.field = field
        self.value = value
        self.expected = expected

        if message:
            self.message = message
        else:
            self.message = f"Invalid value for '{field}': {value}."
            if expected:
                self.message += f' Expected: {expected}.'

        super().__init__(self.message)


def _bounds(field: str, value: int, min_val: int, max_val: int) -> None:
    """Helper to check if value falls within an inclusive range.

    :param field: Field name to check.
    :param value: Field value to check.
    :param min_val: Minimum valid value.
    :param max_val: Maximum valid value.
    :raises CodecValidationError: If value is out of bounds.
    """
    if not (min_val <= value <= max_val):
        raise CodecValidationError(
            field, value, f'between {min_val} and {max_val}'
        )


def gmspr_validate(
    meta: my_model.GmsprMeta, frames: col.Sequence[bytes]
) -> None:
    """Validate sprite metadata against its frame payload and GM8 rules.

    :param meta: Sprite metadata.
    :param frames: List of BGRA frame bytes.
    :raises CodecValidationError: If any value is out
      of bounds or sizes mismatch.
    """
    if meta.version != GMSPR_VER:
        raise CodecValidationError('version', meta.version, '800')

    # dimensions and counts can't be negative, and must fit in i32
    _bounds('width', meta.width, 0, MAX_I32)
    _bounds('height', meta.height, 0, MAX_I32)
    _bounds('subimage_count', meta.subimage_count, 0, MAX_I32)

    if len(frames) != meta.subimage_count:
        raise CodecValidationError(
            'frames array length',
            len(frames),
            str(meta.subimage_count),
            f'Number of frame byte arrays ({len(frames)}) '
            f'does not match subimage_count ({meta.subimage_count}).',
        )

    expected_frame_size = meta.width * meta.height * 4
    for i, frame in enumerate(frames):
        if len(frame) != expected_frame_size:
            raise CodecValidationError(
                f'frames[{i}] size',
                len(frame),
                str(expected_frame_size),
                f'Frame {i} byte length ({len(frame)}) does '
                f'not match width * height * 4 ({expected_frame_size}).',
            )

    # origin may be any number (doesn't have to fit inside bbox)
    _bounds('origin_x', meta.origin_x, MIN_I32, MAX_I32)
    _bounds('origin_y', meta.origin_y, MIN_I32, MAX_I32)

    # enum and boolean checks
    _bounds('mask_kind', meta.mask_kind, 0, 3)
    _bounds('mask_tolerance', meta.mask_tolerance, 0, 255)
    _bounds('separate_masks', meta.separate_masks, 0, 1)
    _bounds('bbox_kind', meta.bbox_kind, 0, 2)

    # bboxes aren't checked on right>left
    _bounds('bbox_left', meta.bbox_left, MIN_I32, MAX_I32)
    _bounds('bbox_right', meta.bbox_right, MIN_I32, MAX_I32)
    _bounds('bbox_bottom', meta.bbox_bottom, MIN_I32, MAX_I32)
    _bounds('bbox_top', meta.bbox_top, MIN_I32, MAX_I32)


def gmbck_validate(meta: my_model.GmbckMeta, pixels: bytes) -> None:
    """Validate background metadata against its pixel payload and GM8 rules.

    :param meta: Background metadata.
    :param pixels: Raw BGRA pixel bytes.
    :raises CodecValidationError: If any value is out
      of bounds or sizes mismatch.
    """
    if meta.version != GMBCK_VER:
        raise CodecValidationError('version', meta.version, '710')
    if meta.image_version != GMBCK_IM_VER:
        raise CodecValidationError('image_version', meta.image_version, '800')

    _bounds('use_as_tile', meta.use_as_tile, 0, 1)
    _bounds('width', meta.width, 0, MAX_I32)
    _bounds('height', meta.height, 0, MAX_I32)

    expected_size = meta.width * meta.height * 4
    if len(pixels) != expected_size:
        raise CodecValidationError(
            'pixels size',
            len(pixels),
            str(expected_size),
            f'Pixel byte length ({len(pixels)}) does not '
            f'match width * height * 4 ({expected_size}).',
        )

    _bounds('tile_width', meta.tile_width, 0, MAX_I32)
    _bounds('tile_height', meta.tile_height, 0, MAX_I32)
    _bounds('tile_h_offset', meta.tile_h_offset, MIN_I32, MAX_I32)
    _bounds('tile_v_offset', meta.tile_v_offset, MIN_I32, MAX_I32)
    _bounds('tile_h_sep', meta.tile_h_sep, MIN_I32, MAX_I32)
    _bounds('tile_v_sep', meta.tile_v_sep, MIN_I32, MAX_I32)
